package com.hpp.mapper;

import com.hpp.bean.UserT;
import com.hpp.bean.UserTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_t
	 * 
	 * @mbggenerated Mon Dec 04 12:40:59 CST 2017
	 */
	int countByExample(UserTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_t
	 * 
	 * @mbggenerated Mon Dec 04 12:40:59 CST 2017
	 */
	int deleteByExample(UserTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_t
	 * 
	 * @mbggenerated Mon Dec 04 12:40:59 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_t
	 * 
	 * @mbggenerated Mon Dec 04 12:40:59 CST 2017
	 */
	int insert(UserT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_t
	 * 
	 * @mbggenerated Mon Dec 04 12:40:59 CST 2017
	 */
	int insertSelective(UserT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_t
	 * 
	 * @mbggenerated Mon Dec 04 12:40:59 CST 2017
	 */
	List<UserT> selectByExample(UserTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_t
	 * 
	 * @mbggenerated Mon Dec 04 12:40:59 CST 2017
	 */
	UserT selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_t
	 * 
	 * @mbggenerated Mon Dec 04 12:40:59 CST 2017
	 */
	int updateByExampleSelective(@Param("record") UserT record,
			@Param("example") UserTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_t
	 * 
	 * @mbggenerated Mon Dec 04 12:40:59 CST 2017
	 */
	int updateByExample(@Param("record") UserT record,
			@Param("example") UserTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_t
	 * 
	 * @mbggenerated Mon Dec 04 12:40:59 CST 2017
	 */
	int updateByPrimaryKeySelective(UserT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_t
	 * 
	 * @mbggenerated Mon Dec 04 12:40:59 CST 2017
	 */
	int updateByPrimaryKey(UserT record);

	/**
	 * 查询所有user
	 * @return
	 */
	UserT selectAllUser();
}